name: jrai-apps

services:
  gateway:
    build:
      context: ..
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - jrai
      - jrai-main

networks:
  jrai:
    external: true
  jrai-main:
    driver: bridge
