name: jrai-apps

services:
  gateway:
    build:
      context: ..
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT}
      - GATEWAY_HOST=${GATEWAY_HOST}
      - GATEWAY_ALLOWED_ORIGINS=${GATEWAY_ALLOWED_ORIGINS}
      - GATEWAY_NODE_ENV=${GATEWAY_NODE_ENV}
      - GATEWAY_COOKIE_DOMAIN=${GATEWAY_COOKIE_DOMAIN}
      - GATEWAY_COOKIE_SECRET=${GATEWAY_COOKIE_SECRET}
      - GATEWAY_COOKIE_EXPIRE_TTL=${GATEWAY_COOKIE_EXPIRE_TTL}
      - AUTH_GRPC_URL=${AUTH_GRPC_URL}
      - ACCOUNT_GRPC_URL=${ACCOUNT_GRPC_URL}
      - STORAGE_GRPC_URL=${STORAGE_GRPC_URL}
      - AICORE_GRPC_URL=${AICORE_GRPC_URL}
      - JOB_GRPC_URL=${JOB_GRPC_URL}
      - PAYMENT_GRPC_URL=${PAYMENT_GRPC_URL}
      - GATEWAY_JWT_SECRET=${GATEWAY_JWT_SECRET}
      - GATEWAY_OAUTH_ID=${GATEWAY_OAUTH_ID}
      - GATEWAY_OAUTH_SECRET=${GATEWAY_OAUTH_SECRET}
      - GATEWAY_OAUTH_CALLBACK_URL=${GATEWAY_OAUTH_CALLBACK_URL}
      - GATEWAY_OAUTH_REDIRECT_URL=${GATEWAY_OAUTH_REDIRECT_URL}
      - GATEWAY_OAUTH_TOKEN_KEY=${GATEWAY_OAUTH_TOKEN_KEY}
      - GATEWAY_RMQ_URL=${GATEWAY_RMQ_URL}
      - GATEWAY_RMQ_AI_RESUME_QUEUE=${GATEWAY_RMQ_AI_RESUME_QUEUE}
      - GATEWAY_RMQ_AI_EXCHANGE_QUEUE=${GATEWAY_RMQ_AI_EXCHANGE_QUEUE}
      - GATEWAY_REDIS_USER=${GATEWAY_REDIS_USER}
      - GATEWAY_REDIS_HOST=${GATEWAY_REDIS_HOST}
      - GATEWAY_REDIS_PASSWORD=${GATEWAY_REDIS_PASSWORD}
      - GATEWAY_REDIS_PORT=${GATEWAY_REDIS_PORT}
    ports:
      - "5000:5000"
    networks:
      - jrai

  auth-service:
    build:
      context: ..
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - AUTH_GRPC_PORT=${AUTH_GRPC_PORT}
      - AUTH_GRPC_HOST=${AUTH_GRPC_HOST}
      - AUTH_NODE_ENV=${AUTH_NODE_ENV}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_ACCESS_TOKEN_TTL=${AUTH_ACCESS_TOKEN_TTL}
      - AUTH_REFRESH_TOKEN_TTL=${AUTH_REFRESH_TOKEN_TTL}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - AUTH_REDIS_USER=${AUTH_REDIS_USER}
      - AUTH_REDIS_HOST=${AUTH_REDIS_HOST}
      - AUTH_REDIS_PASSWORD=${AUTH_REDIS_PASSWORD}
      - AUTH_REDIS_PORT=${AUTH_REDIS_PORT}
      - AUTH_RMQ_URL=${AUTH_RMQ_URL}
      - AUTH_RMQ_QUEUE=${AUTH_RMQ_QUEUE}
      - PAYMENT_GRPC_URL=${PAYMENT_GRPC_URL}
    ports:
      - "50051:50051"
    networks:
      - jrai

  notification-service:
    build:
      context: ..
      dockerfile: apps/notification-service/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    environment:
      - NOTIFICATION_RMQ_URL=${NOTIFICATION_RMQ_URL}
      - NOTIFICATION_RMQ_QUEUE=${NOTIFICATION_RMQ_QUEUE}
      - NOTIFICATION_NODE_ENV=${NOTIFICATION_NODE_ENV}
      - NOTIFICATION_SMTP_HOST=${NOTIFICATION_SMTP_HOST}
      - NOTIFICATION_SMTP_PORT=${NOTIFICATION_SMTP_PORT}
      - NOTIFICATION_SMTP_USERNAME=${NOTIFICATION_SMTP_USERNAME}
      - NOTIFICATION_SMTP_PASSWORD=${NOTIFICATION_SMTP_PASSWORD}
      - NOTIFICATION_SMTP_FROM_ADDRESS=${NOTIFICATION_SMTP_FROM_ADDRESS}
      - NOTIFICATION_SMTP_SECURE=${NOTIFICATION_SMTP_SECURE}
      - NOTIFICATION_SMTP_RESEND_API_TOKEN=${NOTIFICATION_SMTP_RESEND_API_TOKEN}
      - NOTIFICATION_REDIS_USER=${NOTIFICATION_REDIS_USER}
      - NOTIFICATION_REDIS_HOST=${NOTIFICATION_REDIS_HOST}
      - NOTIFICATION_REDIS_PASSWORD=${NOTIFICATION_REDIS_PASSWORD}
      - NOTIFICATION_REDIS_PORT=${NOTIFICATION_REDIS_PORT}
      - NOTIFICATION_REDIS_BULLMQ_PREFIX=${NOTIFICATION_REDIS_BULLMQ_PREFIX}
    ports:
      - "3003:3003"
    networks:
      - jrai

  ai-core-service:
    build:
      context: ..
      dockerfile: apps/ai-core-service/Dockerfile
    container_name: ai-core-service
    restart: unless-stopped
    environment:
      - AICORE_GRPC_PORT=${AICORE_GRPC_PORT}
      - AICORE_GRPC_HOST=${AICORE_GRPC_HOST}
      - AICORE_NODE_ENV=${AICORE_NODE_ENV}
      - AICORE_DATABASE_URL=${AICORE_DATABASE_URL}
      - AICORE_RMQ_URL=${AICORE_RMQ_URL}
      - AICORE_RMQ_JOB_QUEUE=${AICORE_RMQ_JOB_QUEUE}
    ports:
      - "50053:50053"
    networks:
      - jrai

  ai-service:
    build:
      context: ..
      dockerfile: apps/ai-service/Dockerfile
    container_name: ai-service
    restart: unless-stopped
    environment:
      - AIS_RMQ_URL=${AIS_RMQ_URL}
      - AIS_RMQ_QUEUE=${AIS_RMQ_QUEUE}
      - AIS_RMQ_EXCHANGE_QUEUE=${AIS_RMQ_EXCHANGE_QUEUE}
      - AIS_NODE_ENV=${AIS_NODE_ENV}
      - AIS_REDIS_USER=${AIS_REDIS_USER}
      - AIS_REDIS_HOST=${AIS_REDIS_HOST}
      - AIS_REDIS_PASSWORD=${AIS_REDIS_PASSWORD}
      - AIS_REDIS_PORT=${AIS_REDIS_PORT}
      - AIS_REDIS_BULLMQ_PREFIX=${AIS_REDIS_BULLMQ_PREFIX}
      - AICORE_GRPC_URL=${AICORE_GRPC_URL}
      - PAYMENT_GRPC_URL=${PAYMENT_GRPC_URL}
      - AIS_AI_SERVER_URL=${AIS_AI_SERVER_URL}
      - AIS_AI_API_KEY=${AIS_AI_API_KEY}
    networks:
      - jrai

  payment-service:
    build:
      context: ..
      dockerfile: apps/payment-service/Dockerfile
    container_name: payment-service
    restart: unless-stopped
    environment:
      - PAYMENT_GRPC_PORT=${PAYMENT_GRPC_PORT}
      - PAYMENT_GRPC_HOST=${PAYMENT_GRPC_HOST}
      - PAYMENT_NODE_ENV=${PAYMENT_NODE_ENV}
      - PAYMENT_DATABASE_URL=${PAYMENT_DATABASE_URL}
      - PAYMENT_RMQ_URL=${PAYMENT_RMQ_URL}
      - PAYMENT_RMQ_QUEUE=${PAYMENT_RMQ_QUEUE}
      - PAYMENT_STRIPE_SECRET_KEY=${PAYMENT_STRIPE_SECRET_KEY}
      - PAYMENT_STRIPE_WEBHOOK_SECRET=${PAYMENT_STRIPE_WEBHOOK_SECRET}
      - PAYMENT_APP_URL=${PAYMENT_APP_URL}
    ports:
      - "50055:50055"
      - "5001:5001"
    networks:
      - jrai

  storage-service:
    build:
      context: ..
      dockerfile: apps/storage-service/Dockerfile
    container_name: storage-service
    restart: unless-stopped
    environment:
      - STORAGE_GRPC_PORT=${STORAGE_GRPC_PORT}
      - STORAGE_GRPC_HOST=${STORAGE_GRPC_HOST}
      - STORAGE_NODE_ENV=${STORAGE_NODE_ENV}
      - STORAGE_RMQ_URL=${STORAGE_RMQ_URL}
      - STORAGE_RMQ_QUEUE=${STORAGE_RMQ_QUEUE}
      - STORAGE_AWS_REGION=${STORAGE_AWS_REGION}
      - STORAGE_AWS_ACCESS_KEY_ID=${STORAGE_AWS_ACCESS_KEY_ID}
      - STORAGE_AWS_SECRET_ACCESS_KEY=${STORAGE_AWS_SECRET_ACCESS_KEY}
      - STORAGE_AWS_BUCKET_NAME=${STORAGE_AWS_BUCKET_NAME}
      - STORAGE_AWS_ENDPOINT=${STORAGE_AWS_ENDPOINT}
      - STORAGE_AWS_FORCE_PATH_STYLE=${STORAGE_AWS_FORCE_PATH_STYLE}
    ports:
      - "50052:50052"
    networks:
      - jrai

  jobs-service:
    build:
      context: ..
      dockerfile: apps/jobs-service/Dockerfile
    container_name: jobs-service
    restart: unless-stopped
    environment:
      - JOBS_GRPC_PORT=${JOBS_GRPC_PORT}
      - JOBS_GRPC_HOST=${JOBS_GRPC_HOST}
      - JOBS_NODE_ENV=${JOBS_NODE_ENV}
      - JOBS_DATABASE_URL=${JOBS_DATABASE_URL}
      - JOBS_RMQ_URL=${JOBS_RMQ_URL}
      - JOBS_RMQ_QUEUE=${JOBS_RMQ_QUEUE}
    ports:
      - "50054:50054"
    networks:
      - jrai

  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/Dockerfile
      args:
        - NEXT_PUBLIC_APP_URL=${FRONTEND_NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_API_URL=${FRONTEND_NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WEBSOCKET_URL=${FRONTEND_NEXT_PUBLIC_WEBSOCKET_URL}
        - NEXT_PUBLIC_OAUTH_ID=${FRONTEND_NEXT_PUBLIC_OAUTH_ID}
        - NEXT_PUBLIC_OAUTH_SECRET=${FRONTEND_NEXT_PUBLIC_OAUTH_SECRET}
        - NEXT_PUBLIC_OAUTH_REDIRECT_PATH=${FRONTEND_NEXT_PUBLIC_OAUTH_REDIRECT_PATH}
        - NEXT_PUBLIC_OAUTH_ROOT_URL=${FRONTEND_NEXT_PUBLIC_OAUTH_ROOT_URL}
        - NEXT_PUBLIC_OAUTH_API_URL=${FRONTEND_NEXT_PUBLIC_OAUTH_API_URL}
        - NEXT_PUBLIC_STORAGE_URL=${FRONTEND_NEXT_PUBLIC_STORAGE_URL}
    container_name: frontend

    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - jrai
    depends_on:
      - gateway

networks:
  jrai:
    external: true
    name: jrai-infrastructure_jrai
