name: jrai-infrastructure

services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123123
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - jrai
  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - jrai
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - jrai
  minio:
    image: quay.io/minio/minio:latest
    container_name: storage-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SCANNER_SPEED: slow
    volumes:
      - storage_minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - jrai

volumes:
  redis_data:
  rabbitmq_data:
  storage_minio_data:
  postgres_data:

networks:
  jrai:
