name: jrai-frontend

services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
      args:
        - NEXT_PUBLIC_APP_URL=${FRONTEND_NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_API_URL=${FRONTEND_NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WEBSOCKET_URL=${FRONTEND_NEXT_PUBLIC_WEBSOCKET_URL}
        - NEXT_PUBLIC_OAUTH_ID=${FRONTEND_NEXT_PUBLIC_OAUTH_ID}
        - NEXT_PUBLIC_OAUTH_SECRET=${FRONTEND_NEXT_PUBLIC_OAUTH_SECRET}
        - NEXT_PUBLIC_OAUTH_REDIRECT_PATH=${FRONTEND_NEXT_PUBLIC_OAUTH_REDIRECT_PATH}
        - NEXT_PUBLIC_OAUTH_ROOT_URL=${FRONTEND_NEXT_PUBLIC_OAUTH_ROOT_URL}
        - NEXT_PUBLIC_OAUTH_API_URL=${FRONTEND_NEXT_PUBLIC_OAUTH_API_URL}
        - NEXT_PUBLIC_STORAGE_URL=${FRONTEND_NEXT_PUBLIC_STORAGE_URL}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - jrai

networks:
  jrai:
    external: true
    name: jrai-infrastructure_jrai
