name: jrai-storage-service

services:
  storage-service:
    build:
      context: ../..
      dockerfile: apps/storage-service/Dockerfile
    container_name: storage-service
    restart: unless-stopped
    environment:
      - STORAGE_GRPC_PORT=${STORAGE_GRPC_PORT}
      - GRPC_HOST=${GRPC_HOST}
      - NODE_ENV=${NODE_ENV}
      - RMQ_URL=${RMQ_URL}
      - STORAGE_RMQ_QUEUE=${STORAGE_RMQ_QUEUE}
      - STORAGE_AWS_REGION=${STORAGE_AWS_REGION}
      - STORAGE_AWS_ACCESS_KEY_ID=${STORAGE_AWS_ACCESS_KEY_ID}
      - STORAGE_AWS_SECRET_ACCESS_KEY=${STORAGE_AWS_SECRET_ACCESS_KEY}
      - STORAGE_AWS_BUCKET_NAME=${STORAGE_AWS_BUCKET_NAME}
      - STORAGE_AWS_ENDPOINT=${STORAGE_AWS_ENDPOINT}
      - STORAGE_AWS_FORCE_PATH_STYLE=${STORAGE_AWS_FORCE_PATH_STYLE}
    ports:
      - "50052:50052"
    networks:
      - jrai

networks:
  jrai:
    external: true
    name: jrai-infrastructure_jrai
