name: jrai-notification-service

services:
  notification-service:
    build:
      context: ../..
      dockerfile: apps/notification-service/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    environment:
      - RMQ_URL=${RMQ_URL}
      - NOTIFICATION_RMQ_QUEUE=${NOTIFICATION_RMQ_QUEUE}
      - NODE_ENV=${NODE_ENV}
      - NOTIFICATION_SMTP_HOST=${NOTIFICATION_SMTP_HOST}
      - NOTIFICATION_SMTP_PORT=${NOTIFICATION_SMTP_PORT}
      - NOTIFICATION_SMTP_USERNAME=${NOTIFICATION_SMTP_USERNAME}
      - NOTIFICATION_SMTP_PASSWORD=${NOTIFICATION_SMTP_PASSWORD}
      - NOTIFICATION_SMTP_FROM_ADDRESS=${NOTIFICATION_SMTP_FROM_ADDRESS}
      - NOTIFICATION_SMTP_SECURE=${NOTIFICATION_SMTP_SECURE}
      - NOTIFICATION_SMTP_RESEND_API_TOKEN=${NOTIFICATION_SMTP_RESEND_API_TOKEN}
      - REDIS_USER=${REDIS_USER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - NOTIFICATION_REDIS_BULLMQ_PREFIX=${NOTIFICATION_REDIS_BULLMQ_PREFIX}
    ports:
      - "3003:3003"
    networks:
      - jrai

networks:
  jrai:
    external: true
    name: jrai-infrastructure_jrai
