export interface IFaq {
  question: string;
  answer: string;
}

export const jobSearchFaqs: IFaq[] = [
  {
    question: 'How does the AI determine if I’m a good fit for a role?',
    answer:
      'Instead of simple keyword matching, our AI uses Natural Language Processing (NLP) to understand the context of your experience. It compares the complexity of your past projects with the technical requirements of the job to find high-probability matches.',
  },
  {
    question: 'Does the AI apply to jobs automatically on my behalf?',
    answer:
      'Yes, depending on your plan. The AI can handle the repetitive data entry of applications, ensuring your profile is submitted to relevant roles the moment they go live, giving you a significant head start over manual applicants.',
  },
  {
    question: 'What exactly happens during the 3-day trial period?',
    answer:
      "The 3-day trial provides unrestricted access to our 'Pro' features, including AI resume tailoring and automated job tracking. It is designed to show you the volume and quality of opportunities our system can surface before you commit to a subscription.",
  },
  {
    question: 'How does the billing transition work after the trial?',
    answer:
      'To prevent a lapse in your active job applications, the trial automatically converts to a monthly subscription at the end of the 72-hour period. You can cancel at any time before the deadline to avoid being charged.',
  },
  {
    question: "Will my resume look 'robotic' if generated by AI?",
    answer:
      'Not at all. Our models are trained on successful, human-vetted resumes. The AI focuses on clarifying your impact and quantifying your achievements, ensuring the output remains professional, readable, and authentic to your voice.',
  },
  {
    question: 'Is my personal data and resume history secure?',
    answer:
      'Security is our priority. Your data is encrypted at rest and in transit. We use your information strictly to calibrate the matching engine for your personal search; we never sell your data to third-party recruiters.',
  },
  {
    question: 'Can I use the tool to find remote work specifically?',
    answer:
      "Yes. The AI allows you to set abstract preferences, such as 'Remote-First' or 'Asynchronous Cultures,' filtering the global job market to find companies whose working style matches your lifestyle.",
  },
  {
    question: 'What if I find a job mid-month? Can I get a refund?',
    answer:
      "While we don't offer prorated refunds, you can cancel your subscription immediately upon finding a role. You will retain access to your tailored resumes and application history until the end of your current billing cycle.",
  },
  {
    question: 'Does the AI help with interview preparation?',
    answer:
      "Our 'Premium' tier includes an AI coach that generates mock interview questions based specifically on the job description you are targeting, helping you practice your responses and refine your talking points.",
  },
  {
    question: "Why do some jobs require a 'Tailored' resume while others don't?",
    answer:
      "High-competition roles often use strict AI filters. Our system identifies these 'high-barrier' postings and recommends a tailored resume version to ensure your most relevant skills are prioritized for those specific algorithms.",
  },
];
